<?php

namespace Modules\Production\App\Repositories;
use Doctrine\ORM\EntityRepository;



/**
 * ItemKeyValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
}
