<?php

namespace Modules\Production\App\Repositories;
use Doctrine\ORM\EntityRepository;
use Modules\Production\App\Entities\Item;
use Modules\Production\App\Entities\ProductionBatch;
use Modules\Production\App\Entities\ProductionReceiveBatch;
use Modules\Production\App\Entities\ProductionReceiveBatchItem;
use Modules\Production\App\Entities\ProductionStock;
use Modules\Production\App\Entities\ProductionWorkOrder;
use Modules\Production\App\Entities\ProductionWorkOrderItem;

/**
 * eRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionReceiveBatchRepository extends EntityRepository
{


}
