<?php

namespace Modules\Production\App\Repositories;
use App\Entity\Application\Production;
use Appstore\Bundle\TallyBundle\Entity\e;
use Doctrine\ORM\EntityRepository;
use Modules\Production\App\Entities\Item;
use Modules\Production\App\Entities\ProductionBatch;
use Modules\Production\App\Entities\ProductionStock;
use Modules\Production\App\Entities\ProductionWorkOrder;
use Modules\Production\App\Entities\ProductionWorkOrderItem;

/**
 * eRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionBatchRepository extends EntityRepository
{

    public function findWithSearch( $config, $parameter , $data ): array
    {


        if (!empty($parameter['orderBy'])) {
            $sortBy = $parameter['orderBy'];
            $order = $parameter['order'];
        }
        $startDate = isset($data['startDate'])  ? $data['startDate'].' 00:00:00' :'';
        $endDate =   isset($data['endDate'])  ? $data['endDate'].' 23:59:59' :'';


        $qb = $this->createQueryBuilder('e');
        $qb->leftJoin('e.vendor','vendor');
        $qb->leftJoin('e.createdBy','user');
        $qb->select('e.id as id','e.created as created','e.issueDate as issueDate','e.invoice as invoice', 'e.process as process', 'e.mode as mode', 'e.status as status');
        $qb->addSelect('vendor.companyName as companyName');
        $qb->addSelect('user.username as username');
        $qb->where("e.config = :config")->setParameter('config', $config);
        $qb->setFirstResult($parameter['offset']);
        $qb->setMaxResults($parameter['limit']);
        if ($parameter['orderBy']){
            $qb->orderBy($sortBy, $order);
        }else{
            $qb->orderBy('e.created', 'DESC');
        }
        $result = $qb->getQuery()->getArrayResult();
        return  $result;

    }

    public function insertUpdate(ProductionWorkOrder $workOrder, $data)
    {

        $em = $this->_em;
        $stock =  $em->getRepository();
        if($stock){
         $entity = $stock;
        }else{
         $entity = new ProductionWorkOrderItem();
        }
        $entity->setProductionWorkOrder($workOrder);
        $entity->setProductionItem($productionItem);
        $entity->setProductionItem($productionItem);
        $em->persist($entity);
        $em->flush();
    }

    public function insertProductionInventory(Production $config,Item $item)
    {

        $em = $this->_em;
        $inventoryItem = $this->findOneBy(array('item'=>$item));
        $productionQnt = $em->getRepository('TerminalbdInventoryBundle:ProductionIssue')->getIssueItem($item);
        if($inventoryItem){
            $entity = $inventoryItem;
        }else{
            $entity = new ProductionInventory();
        }
        $unit = !empty($item->getUnit() && !empty($item->getUnit()->getName())) ? $item->getUnit()->getName():'';
        $entity->setConfig($config);
        $entity->setItem($item);
        $entity->setName($item->getName());
        $entity->setUom($unit);
        $entity->setQuantity($productionQnt);
        $em->persist($entity);
        $em->flush();
        $this->remainingQnt($entity);

    }



}
