<?php

namespace Modules\Core\App\Repositories;

use Doctrine\ORM\EntityRepository;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Modules\Core\App\Entities\Location;
use Modules\Core\App\Filters\CustomerFilter;
use Modules\Core\App\Models\CustomerModel;


/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository {



    public function listWithSearch(array $queryParams = [])
    {
        $entity = DB::table("cor_locations as e")
            ->select(DB::raw("e.id as id,e.name as name"))->where('e.level', 2)->limit(5000)->get();
        return $entity;
    }



}
