<?php


namespace Modules\Domain\App\Repositories;
use Doctrine\ORM\EntityRepository;


/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplatingRepository extends EntityRepository
{

}
