<?php

namespace Modules\Inventory\App\Repositories;
use Appstore\Bundle\AccountingBundle\Entity\AccountSales;
use Modules\Inventory\App\Entities\BusinessInvoice;
use Modules\Inventory\App\Entities\BusinessInvoiceTransaction;
use Modules\Core\App\Entities\User;
use Doctrine\ORM\EntityRepository;


/**
 * BusinessBusinessInvoiceTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessInvoiceTransactionRepository extends EntityRepository
{

    public function todaySalesOverview(User $user , $data , $previous ='', $mode='')
    {

        if (empty($data)) {
            $datetime = new \DateTime("now");
            $data['startDate'] = $datetime->format('Y-m-d 00:00:00');
            $data['endDate'] = $datetime->format('Y-m-d 23:59:59');
        } elseif (!empty($data['startDate']) and !empty($data['endDate'])) {
            $data['startDate'] = date('Y-m-d', strtotime($data['startDate']));
            $data['endDate'] = date('Y-m-d', strtotime($data['endDate']));
        }

        $hospital = $user->getGlobalOption()->getBusinessConfig()->getId();
        $qb = $this->createQueryBuilder('it');
        $qb->join('it.businessInvoice', 'e');
        $qb->select('sum(it.total) as total ,sum(it.discount) as discount , sum(it.payment) as payment');
        $qb->where('e.hospitalConfig = :hospital')->setParameter('hospital', $hospital);
        if ($previous == 'true'){

            if (!empty($data['startDate'])) {
                $qb->andWhere("it.updated >= :startDate");
                $qb->setParameter('startDate', $data['startDate'] . ' 00:00:00');
            }
            if (!empty($data['endDate'])) {
                $qb->andWhere("it.updated <= :endDate");
                $qb->setParameter('endDate', $data['endDate'] . ' 23:59:59');
            }
            if (!empty($data['startDate'])) {
                $qb->andWhere("e.created >= :startDate");
                $qb->setParameter('startDate', $data['startDate'] . ' 00:00:00');
            }
            if (!empty($data['endDate'])) {
                $qb->andWhere("e.created <= :endDate");
                $qb->setParameter('endDate', $data['endDate'] . ' 23:59:59');
            }

        }elseif ($previous == 'false'){

            if (!empty($data['startDate'])) {
                $qb->andWhere("e.created < :startDate");
                $qb->setParameter('startDate', $data['startDate'] . ' 00:00:00');
            }
            if (!empty($data['startDate'])) {
                $qb->andWhere("it.updated >= :startDate");
                $qb->setParameter('startDate', $data['startDate'] . ' 00:00:00');
            }
            if (!empty($data['endDate'])) {
                $qb->andWhere("it.updated <= :endDate");
                $qb->setParameter('endDate', $data['endDate'] . ' 23:59:59');
            }

        }
        if (!empty($mode)){
            $qb->andWhere('e.invoiceMode = :mode')->setParameter('mode', $mode);
        }
        $qb->andWhere('it.process = :process')->setParameter('process', 'Done');
        $result = $qb->getQuery()->getOneOrNullResult();
        $total = !empty($result['total']) ? $result['total'] :0;
        $discount = !empty($result['discount']) ? $result['discount'] :0;
        $receive = !empty($result['payment']) ? $result['payment'] :0;
        $data = array('total'=> $total ,'discount'=> $discount ,'receive'=> $receive);
        return $data;
    }

    public function handleDateRangeFind($qb,$data)
    {
        if(empty($data)){
            $datetime = new \DateTime("now");
            $data['startDate'] = $datetime->format('Y-m-d 00:00:00');
            $data['endDate'] = $datetime->format('Y-m-d 23:59:59');
        }else{
            $data['startDate'] = date('Y-m-d',strtotime($data['startDate']));
            $data['endDate'] = date('Y-m-d',strtotime($data['endDate']));
        }

        if (!empty($data['startDate']) ) {
            $qb->andWhere("ip.updated >= :startDate");
            $qb->setParameter('startDate', $data['startDate'].' 00:00:00');
        }
        if (!empty($data['endDate'])) {
            $qb->andWhere("ip.updated <= :endDate");
            $qb->setParameter('endDate', $data['endDate'].' 23:59:59');
        }
    }


    public function findWithTransactionOverview(User $user, $data)
    {
        $hospital = $user->getGlobalOption()->getBusinessConfig()->getId();
        $qb = $this->createQueryBuilder('ip');
        $qb->join('ip.businessInvoice','e');
        $qb->leftJoin('ip.transactionMethod','p');
        $qb->select('sum(ip.payment) as paymentTotal');
        $qb->addSelect('p.name as transName');
        $qb->where('e.hospitalConfig = :hospital')->setParameter('hospital', $hospital);
        if (!empty($mode)){
            $qb->andWhere('e.invoiceMode = :mode')->setParameter('mode', $mode);
        }
        $qb->andWhere("e.process IN (:process)");
        $qb->setParameter('process', array('Done','Paid','In-progress','Diagnostic','Admitted'));
        $this->handleDateRangeFind($qb,$data);
        $qb->groupBy('p.id');
        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }



    public function initialInsertBusinessInvoiceTransaction(BusinessInvoice $invoice){

        $code = $this->getLastCode($invoice);
        $entity = New BusinessInvoiceTransaction();
        $entity->setBusinessInvoice($invoice);
        $entity->setCode($code + 1);
        $transactionCode = sprintf("%s", str_pad($entity->getCode(),2, '0', STR_PAD_LEFT));
        $entity->setProcess('Done');
        $entity->setTransactionCode($transactionCode);
        $entity->setDiscount($invoice->getDiscount());
        $entity->setTotal($invoice->getSubTotal());
        $entity->setPayment($invoice->getPayment());
        $this->_em->persist($entity);
        $this->_em->flush($entity);
        return $entity;

    }

    public function admissionPaymentTransaction(BusinessInvoice $invoice,$data){

        $code = $this->getLastCode($invoice);
        $entity = New BusinessInvoiceTransaction();
        $entity->setBusinessInvoice($invoice);
        $entity->setCode($code + 1);
        $transactionCode = sprintf("%s", str_pad($entity->getCode(),2, '0', STR_PAD_LEFT));
        $entity->setTransactionCode($transactionCode);
        $entity->setDiscount($data['discount']);
        $entity->setPayment($data['payment']);
        $entity->setProcess('In-progress');
        $transactionMethod = $this->_em->getRepository('SettingToolBundle:TransactionMethod')->find(1);
        $entity->setTransactionMethod($transactionMethod);
        $this->_em->persist($entity);
        $this->_em->flush($entity);
        return $entity;

    }



    public function insertAdmissionTransaction(BusinessInvoiceTransaction $entity, $data)
    {

        $process = $data['process'];
        $invoice = $entity->getBusinessInvoice();
        $entity->setProcess($process);
        $entity->setPayment($data['discount']);
        $entity->setPayment($data['payment']);
        $entity->setTransactionMethod($invoice->getTransactionMethod());
        $entity->setAccountBank($invoice->getAccountBank());
        $entity->setPaymentCard($invoice->getPaymentCard());
        $entity->setCardNo($invoice->getCardNo());
        $entity->setBank($invoice->getBank());
        $entity->setAccountMobileBank($invoice->getAccountMobileBank());
        $entity->setPaymentMobile($invoice->getPaymentMobile());
        $entity->setTransactionId($invoice->getTransactionId());
        $entity->setComment($invoice->getComment());
        if ($invoice->getBusinessConfig()->getVatEnable() == 1 && $invoice->getBusinessConfig()->getVatPercentage() > 0) {
            $vat = $this->getCulculationVat($invoice, $entity->getPayment());
            $entity->setVat($vat);
        }
        $this->_em->persist($entity);
        $this->_em->flush($entity);

    }
    public function insertTransaction(BusinessInvoice $invoice)
    {
            $entity = New BusinessInvoiceTransaction();
            $code = $this->getLastCode($invoice);
            $entity->setBusinessInvoice($invoice);
            $entity->setCode($code + 1);
            $transactionCode = sprintf("%s", str_pad($entity->getCode(),2, '0', STR_PAD_LEFT));
            $entity->setTransactionCode($transactionCode);
            $entity->setProcess('Done');
            $entity->setDiscount($invoice->getDiscount());
            $entity->setPayment($invoice->getPayment());
            $entity->setTotal($invoice->getSubTotal());
            $entity->setTransactionMethod($invoice->getTransactionMethod());
            $entity->setAccountBank($invoice->getAccountBank());
            $entity->setPaymentCard($invoice->getPaymentCard());
            $entity->setCardNo($invoice->getCardNo());
            $entity->setBank($invoice->getBank());
            $entity->setAccountMobileBank($invoice->getAccountMobileBank());
            $entity->setPaymentMobile($invoice->getPaymentMobile());
            $entity->setTransactionId($invoice->getTransactionId());
            $entity->setComment($invoice->getComment());
            if ($invoice->getBusinessConfig()->getVatEnable() == 1 && $invoice->getBusinessConfig()->getVatPercentage() > 0) {
                $vat = $this->getCulculationVat($invoice, $entity->getPayment());
                $entity->setVat($vat);
            }
            $this->_em->persist($entity);
            $this->_em->flush($entity);
            if($invoice->getPayment() > 0){
                $accountBusinessInvoice = $this->_em->getRepository('AccountingBundle:AccountSales')->insertAccountBusinessInvoice($entity);
                $this->_em->getRepository('AccountingBundle:Transaction')->hmsSalesTransaction($entity, $accountBusinessInvoice);
            }


    }
    public function insertPaymentTransaction(BusinessInvoice $invoice, $data)
    {
        $entity = New BusinessInvoiceTransaction();
        $code = $this->getLastCode($invoice);
        $entity->setBusinessInvoice($invoice);
        $entity->setCode($code + 1);
        $transactionCode = sprintf("%s", str_pad($entity->getCode(),2, '0', STR_PAD_LEFT));
        $entity->setTransactionCode($transactionCode);
        $entity->setProcess($data['process']);
        $entity->setDiscount($data['discount']);
        $entity->setPayment($data['payment']);
        $entity->setTransactionMethod($invoice->getTransactionMethod());
        $entity->setAccountBank($invoice->getAccountBank());
        $entity->setPaymentCard($invoice->getPaymentCard());
        $entity->setCardNo($invoice->getCardNo());
        $entity->setBank($invoice->getBank());
        $entity->setAccountMobileBank($invoice->getAccountMobileBank());
        $entity->setPaymentMobile($invoice->getPaymentMobile());
        $entity->setTransactionId($invoice->getTransactionId());
        $entity->setComment($invoice->getComment());
        if ($invoice->getBusinessConfig()->getVatEnable() == 1 && $invoice->getBusinessConfig()->getVatPercentage() > 0) {
            $vat = $this->getCulculationVat($invoice, $entity->getPayment());
            $entity->setVat($vat);
        }
        $this->_em->persist($entity);
        $this->_em->flush($entity);

    }

    public function admissionBusinessInvoiceTransactionUpdate(BusinessInvoiceTransaction $entity )
    {
        $invoice = $entity->getBusinessInvoice();
        if ($invoice->getBusinessConfig()->getVatEnable() == 1 && $invoice->getBusinessConfig()->getVatPercentage() > 0) {
            $vat = $this->getCulculationVat($invoice, $entity->getPayment());
            $entity->setVat($vat);
        }
        if(empty($entity->getTransactionMethod())){
            $entity->setTransactionMethod($this->_em->getRepository('SettingToolBundle:TransactionMethod')->find(1));
        }
        $this->_em->persist($entity);
        $this->_em->flush($entity);
        $accountBusinessInvoice = $this->_em->getRepository('AccountingBundle:AccountSales')->insertAccountBusinessInvoice($entity);
        $this->_em->getRepository('AccountingBundle:Transaction')->hmsSalesTransaction($entity, $accountBusinessInvoice);

    }

    public function hmsSalesTransactionReverse(BusinessInvoice $entity)
    {


        $em = $this->_em;

        if(!empty($entity->getAccountSales())){
            /* @var AccountSales $sales*/
            foreach ($entity->getAccountSales() as $sales ){

                $globalOption = $sales->getGlobalOption()->getId();
                $accountRefNo = $sales->getAccountRefNo();
                $transaction = $em->createQuery("DELETE AccountingBundle:Transaction e WHERE e.globalOption = ".$globalOption ." AND e.accountRefNo =".$accountRefNo." AND e.processHead = 'Sales'");
                $transaction->execute();
                $accountCash = $em->createQuery("DELETE AccountingBundle:AccountCash e WHERE e.globalOption = ".$globalOption ." AND e.accountRefNo =".$accountRefNo." AND e.processHead = 'Sales'");
                $accountCash->execute();
            }
        }

        $accountCash = $em->createQuery('DELETE AccountingBundle:AccountSales e WHERE e.businessBusinessInvoices = '.$entity->getId());
        if(!empty($accountCash)){
            $accountCash->execute();
        }

        $transaction = $em->createQuery('DELETE BusinessBundle:BusinessInvoiceTransaction e WHERE e.businessBusinessInvoice = '.$entity->getId());
        if(!empty($transaction)) {
            $transaction->execute();
        }
    }

    public function hmsAdmissionSalesTransactionReverse(BusinessInvoice $entity)
    {

        $em = $this->_em;

        if(!empty($entity->getAccountSales())){
            /* @var AccountSales $sales*/
            foreach ($entity->getAccountSales() as $sales ){

                $globalOption = $sales->getGlobalOption()->getId();
                $accountRefNo = $sales->getAccountRefNo();
                $transaction = $em->createQuery("DELETE AccountingBundle:Transaction e WHERE e.globalOption = ".$globalOption ." AND e.accountRefNo =".$accountRefNo." AND e.processHead = 'Sales'");
                $transaction->execute();
                $accountCash = $em->createQuery("DELETE AccountingBundle:AccountCash e WHERE e.globalOption = ".$globalOption ." AND e.accountRefNo =".$accountRefNo." AND e.processHead = 'Sales'");
                $accountCash->execute();
            }
        }

        $accountCash = $em->createQuery('DELETE AccountingBundle:AccountSales e WHERE e.businessBusinessInvoices = '.$entity->getId());
        if(!empty($accountCash)){
            $accountCash->execute();
        }

        $qb = $this->createQueryBuilder('it');
        $q = $qb->update()
            ->set('it.process', $qb->expr()->literal('In-progress'))
            ->set('it.revised', $qb->expr()->literal(1))
            ->where('it.businessBusinessInvoice = :invoice')
            ->setParameter('invoice', $entity->getId())
            ->getQuery();
        $q->execute();
    }

    public function updateBusinessInvoiceTransactionDiscount(BusinessInvoice $entity)
    {

        /** @var BusinessInvoiceTransaction $transaction */
        foreach ($entity->getBusinessInvoiceTransactions() as $transaction) {

            $transaction->setDiscount(0);
            $this->_em->persist($transaction);
            $this->_em->flush($transaction);
        }
        foreach ($entity->getBusinessInvoiceTransactions() as $transaction) {

            if( empty($transaction->getPayment()) and empty($transaction->getDiscount())){

                $qb = $this->_em->createQueryBuilder();
                $qb->delete('BusinessBundle:BusinessInvoiceTransaction', 'trans')
                    ->where($qb->expr()->eq('trans.id', ':id'))
                    ->setParameter('id', $transaction->getId());
                $qb->getQuery()->execute();
            }
        }
    }

    public function removePendingTransaction(BusinessInvoice $entity)
    {
        $em = $this->_em;
        $qb = $em->createQueryBuilder();
        $query = $qb->delete('BusinessBundle:BusinessInvoiceTransaction', 'e')
            ->where('e.businessBusinessInvoice = :businessBusinessInvoice')
            ->setParameter('businessBusinessInvoice', $entity->getId())
            ->andWhere('e.process IN (:process)')
            ->setParameter('process',array('Pending','In-progress'))
            ->getQuery();
        if(!empty($query)) {
            $query->execute();
        }
    }

    public function getCulculationVat(BusinessInvoice $invoice, $totalAmount)
    {
        $vat = (($totalAmount * (int)$invoice->getBusinessConfig()->getVatPercentage()) / 100);
        return round($vat);
    }

    public function getBusinessInvoiceTransactionItems(BusinessInvoice $invoice)
    {
        $entities = $invoice->getBusinessInvoiceTransactions();
        $data = '';
        $i = 1;

        /** @var BusinessInvoiceTransaction $transaction */

        foreach ($entities as $transaction) {

            $date = $transaction->getUpdated()->format('d-m-Y');
            $transactionMethod ='';
            if(!empty($transaction->getTransactionMethod())){
                $transactionMethod = $transaction->getTransactionMethod()->getName();
            }
            $data .= '<tr>';
            $data .= '<td class="numeric" >' . $i . '</td>';
            $data .= '<td class="numeric" >' . $date . '</td>';
            $data .= '<td class="numeric" >' . $transactionMethod. '</td>';
            $data .= '<td class="numeric" >' . $transaction->getDiscount() . '</td>';
            $data .= '<td class="numeric" >' . $transaction->getVat() . '</td>';
            $data .= '<td class="numeric" >' . $transaction->getPayment() . '</td>';
            $data .= '<td class="numeric" >' . $transaction->getCreatedBy() . '</td>';

            $i++;
        }
        return $data;
    }

    public function getLastCode(BusinessInvoice $invoice)
    {
        $qb = $this->_em->getRepository('BusinessBundle:BusinessInvoiceTransaction')->createQueryBuilder('s');
        $qb
            ->select('MAX(s.code)')
            ->where('s.businessBusinessInvoice = :invoice')
            ->setParameter('invoice', $invoice->getId());
            $lastCode = $qb->getQuery()->getSingleScalarResult();
        if (empty($lastCode)) {
            return 0;
        }
        return $lastCode;
    }
}
