<?php

namespace Modules\Inventory\App\Repositories;
use Modules\Inventory\App\Entities\BusinessInvoice;
use Modules\Inventory\App\Entities\BusinessInvoiceParticular;
use Modules\Inventory\App\Entities\BusinessParticular;
use Modules\Inventory\App\Entities\BusinessProductionElement;
use Doctrine\ORM\EntityRepository;


/**
 * ProductionElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessProductionExpenseRepository extends EntityRepository
{
    public function removeProductionExpense(BusinessInvoice $invoice)
    {
        $em = $this->_em;

	    if(!empty($invoice->getBusinessInvoiceParticulars())) {

		    /* @var  $item BusinessInvoiceParticular */

		    foreach ($invoice->getBusinessInvoiceParticulars() as $item) {
			    $transaction = $em->createQuery( "DELETE BusinessBundle:BusinessProductionExpense e WHERE e.businessInvoiceParticular ={$item->getId()}");
			    if($transaction){
                    $transaction->execute();
                }
		    }

	    }
	}

}
