<?php

namespace Modules\Inventory\App\Repositories;
use Appstore\Bundle\BusinessBundle\BusinessBundle;
use Modules\Inventory\App\Entities\BusinessBatchParticular;
use Modules\Inventory\App\Entities\BusinessConfig;
use Modules\Inventory\App\Entities\BusinessInvoiceParticular;
useModules\Core\App\Entities\Customer;
use Modules\Inventory\App\Entities\BusinessInvoice;
use Modules\Inventory\App\Entities\BusinessParticular;
use Modules\Core\App\Entities\User;
use Doctrine\ORM\EntityRepository;
use Modules\Domain\App\Entities\GlobalOption;


/**
 * BusinessInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessInvoiceRepository extends EntityRepository
{

    public function getLastInvoice(BusinessConfig $config,$customer)
    {
        $entity = $this->findOneBy(
            array('businessConfig' => $config,'customer' => $customer),
            array('id' => 'DESC')
        );
        return $entity;
    }

    /**
     * @param $qb
     * @param $data
     */

    protected function handleSearchBetween($qb,$data)
    {

        $invoice = isset($data['invoice'])? $data['invoice'] :'';
        $process = isset($data['process'])? $data['process'] :'';
        $customerName = isset($data['name'])? $data['name'] :'';
        $customerMobile = isset($data['mobile'])? $data['mobile'] :'';
        $createdStart = isset($data['createdStart'])? $data['createdStart'] :'';
        $createdEnd = isset($data['createdEnd'])? $data['createdEnd'] :'';
        $startDate = isset($data['startDate'])? $data['startDate'] :'';
        $endDate = isset($data['endDate'])? $data['endDate'] :'';
        $createdBy = isset($data['createdBy'])? $data['createdBy'] :'';
        $condition = isset($data['condition'])? $data['condition'] :'';

        if (!empty($invoice)) {
            $qb->andWhere($qb->expr()->like("e.invoice", "'%$invoice%'"  ));
        }
        if (!empty($customerName)) {
            $qb->join('e.customer','c');
            $qb->andWhere($qb->expr()->like("c.name", "'$customerName%'"  ));
        }
        if (!empty($createdBy)) {
            $qb->andWhere("e.createdBy = :user")->setParameter('user', $createdBy);
        }

        if (!empty($customerMobile)) {
            $qb->join('e.customer','m');
            $qb->andWhere($qb->expr()->like("m.mobile", "'%$customerMobile%'"  ));
        }
        if (!empty($condition)) {
            $qb->andWhere("e.condition = :condition")->setParameter('condition', $condition);
        }
        if (!empty($createdStart)) {
            $compareTo = new \DateTime($createdStart);
            $created =  $compareTo->format('Y-m-d 00:00:00');
            $qb->andWhere("e.created >= :created");
            $qb->setParameter('created', $created);
        }
        if (!empty($createdEnd)) {
            $compareTo = new \DateTime($createdEnd);
            $createdEnd =  $compareTo->format('Y-m-d 23:59:59');
            $qb->andWhere("e.created <= :createdEnd");
            $qb->setParameter('createdEnd', $createdEnd);
        }
        if (!empty($startDate)) {
            $compareTo = new \DateTime($startDate);
            $created =  $compareTo->format('Y-m-d 00:00:00');
            $qb->andWhere("e.created >= :created");
            $qb->setParameter('created', $created);
        }
        if (!empty($endDate)) {
            $compareTo = new \DateTime($endDate);
            $createdEnd =  $compareTo->format('Y-m-d 23:59:59');
            $qb->andWhere("e.created <= :createdEnd");
            $qb->setParameter('createdEnd', $createdEnd);
        }
        if(!empty($process)){
            $qb->andWhere("e.process = :process");
            $qb->setParameter('process', $process);
        }

    }

    public function handleDateRangeFind($qb,$data)
    {
        if(empty($data)){
            $datetime = new \DateTime("now");
            $data['startDate'] = $datetime->format('Y-m-d 00:00:00');
            $data['endDate'] = $datetime->format('Y-m-d 23:59:59');
        }else{
            $data['startDate'] = date('Y-m-d',strtotime($data['startDate']));
            $data['endDate'] = date('Y-m-d',strtotime($data['endDate']));
        }

        if (!empty($data['startDate']) ) {
            $qb->andWhere("it.created >= :startDate");
            $qb->setParameter('startDate', $data['startDate'].' 00:00:00');
        }

        if (!empty($data['endDate'])) {
            $qb->andWhere("it.created <= :endDate");
            $qb->setParameter('endDate', $data['endDate'].' 23:59:59');
        }
    }

    public function reportSalesOverview(User $user ,$data)
    {

        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        if(empty($data)){
            $datetime = new \DateTime("now");
            $start = $datetime->format('Y-m-d 00:00:00');
            $end = $datetime->format('Y-m-d 23:59:59');
        }else{
            $start = date('Y-m-d 00:00:00',strtotime($data['startDate']));
            $end = date('Y-m-d 23:59:59',strtotime($data['endDate']));
        }
        $qb = $this->createQueryBuilder('e');
        $qb->select('sum(e.subTotal) as subTotal , sum(e.total) as total ,sum(e.received) as totalPayment , count(e.id) as totalVoucher, sum(e.due) as totalDue, sum(e.discount) as totalDiscount, sum(e.vat) as totalVat');
        $qb->where('e.businessConfig = :config');
        $qb->setParameter('config', $config);
        $qb->andWhere('e.process IN (:process)');
        $qb->setParameter('process', array('Done','Delivered','Chalan'));
        $qb->andWhere("e.created >= :created");
        $qb->setParameter('created', $start);
        $qb->andWhere("e.created <= :createdEnd");
        $qb->setParameter('createdEnd', $end);
        $summary =  $qb->getQuery()->getOneOrNullResult();
        return $summary;

    }

    public function reportCustomerSales(User $user ,$data)
    {

        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        if(empty($data)){
            $datetime = new \DateTime("now");
            $start = $datetime->format('Y-m-d 00:00:00');
            $end = $datetime->format('Y-m-d 23:59:59');
        }else{
            $start = date('Y-m-d 00:00:00',strtotime($data['startDate']));
            $end = date('Y-m-d 23:59:59',strtotime($data['endDate']));
        }
        $process = "Delivered";
        $config     =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $sql = "SELECT sales.customer_id as customer,c.name as customerName,c.mobile as customerMobile,c.address as customerAddress, SUM(sales.subTotal) AS subTotal, SUM(sales.total) AS total, SUM(sales.discount) AS discount, SUM(sales.received) AS receive, SUM(sales.due) AS due
                FROM business_invoice as sales
                JOIN Customer as c ON c.id = sales.customer_id
                WHERE sales.businessConfig_id = :config AND  sales.process = :process AND date (sales.created) >=:start AND date(sales.created) <=:end
                GROUP BY customer ORDER BY customer ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process',$process);
        $stmt->bindValue('start', $start);
        $stmt->bindValue('end', $end);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $customerSalesSummary = array();
        foreach($result as $row) {
            $id = "{$row['customer']}";
            $customerSalesSummary[$id] = $row;
        }
        return $customerSalesSummary;

    }

    public  function reportSalesItemPurchaseSalesOverview(User $user, $data = array()){


        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        if(empty($data)){
            $datetime = new \DateTime("now");
            $start = $datetime->format('Y-m-d 00:00:00');
            $end = $datetime->format('Y-m-d 23:59:59');
        }else{
            $start = date('Y-m-d 00:00:00',strtotime($data['startDate']));
            $end = date('Y-m-d 23:59:59',strtotime($data['endDate']));
        }
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.businessInvoiceParticulars','si');
        $qb->select('SUM(si.quantity) AS quantity');
        $qb->addSelect('COUNT(si.id) AS totalItem');
        $qb->addSelect('SUM(si.totalQuantity * si.purchasePrice) AS totalPurchase');
        $qb->addSelect('SUM(si.subTotal) AS salesPrice');
        $qb->where('e.businessConfig = :config');
        $qb->setParameter('config', $config);
	    $qb->andWhere('e.process IN (:process)');
	    $qb->setParameter('process', array('Done','Delivered','Chalan'));
        $qb->andWhere("e.created >= :created");
        $qb->setParameter('created', $start);
        $qb->andWhere("e.created <= :createdEnd");
        $qb->setParameter('createdEnd', $end);
        $result = $qb->getQuery()->getOneOrNullResult();
        return $result;
    }

	public function salesReport( User $user , $data)
	{

		$userBranch = $user->getProfile()->getBranches();
		$config =  $user->getGlobalOption()->getBusinessConfig()->getId();

		$qb = $this->createQueryBuilder('e');
		$qb->leftJoin('e.salesBy', 'u');
		$qb->leftJoin('e.transactionMethod', 't');
		$qb->select('u.username as salesBy');
		$qb->addSelect('t.name as transactionMethod');
		$qb->addSelect('e.id as id');
		$qb->addSelect('e.created as created');
		$qb->addSelect('e.process as process');
		$qb->addSelect('e.invoice as invoice');
		$qb->addSelect('(e.due) as due');
		$qb->addSelect('(e.subTotal) as subTotal');
		$qb->addSelect('(e.total) as total');
		$qb->addSelect('(e.received) as payment');
		$qb->addSelect('(e.discount) as discount');
		$qb->addSelect('(e.vat) as vat');
		$qb->where('e.businessConfig = :config');
		$qb->setParameter('config', $config);
		$qb->andWhere('e.process IN (:process)');
		$qb->setParameter('process', array('Done','Delivered','Chalan'));
		if(!empty($userBranch)){
			$qb->andWhere("e.branches =".$userBranch);
		}
		$this->handleSearchBetween($qb,$data);
		$qb->orderBy('e.updated','DESC');
		$result = $qb->getQuery();
		return $result;

	}


	public function salesPurchasePriceReport(User $user,$data,$x)
	{

		$userBranch = $user->getProfile()->getBranches();
		$config =  $user->getGlobalOption()->getBusinessConfig()->getId();

		$ids = array();
		foreach ($x as $y){
			$ids[]=$y['id'];
		}

		$qb = $this->createQueryBuilder('e');
		$qb->join('e.businessInvoiceParticulars','si');
		$qb->select('e.id as salesId');
		$qb->addSelect('SUM(si.totalQuantity * si.purchasePrice ) AS totalPurchaseAmount');
		$qb->where('e.businessConfig = :config');
		$qb->setParameter('config', $config);
		$qb->andWhere('e.process IN (:process)');
		$qb->setParameter('process', array('Done','Delivered','Chalan'));
		$qb->andWhere("e.id IN (:salesId)")->setParameter('salesId', $ids);
		if(!empty($userBranch)){
			$qb->andWhere("e.branches =".$userBranch);
		}
		$this->handleSearchBetween($qb,$data);
		$qb->orderBy('totalPurchaseAmount','DESC');
		$qb->groupBy('salesId');
		$result = $qb->getQuery()->getArrayResult();
		$array= array();
		foreach ($result as $row ){
			$array[$row['salesId']]= $row['totalPurchaseAmount'];
		}
		return $array;
	}

	public  function reportSalesItem(User $user, $data=''){

		$userBranch = $user->getProfile()->getBranches();
		$config =  $user->getGlobalOption()->getMedicineConfig()->getId();
		$group = isset($data['group']) ? $data['group'] :'medicineStock';

		$qb = $this->createQueryBuilder('e');
		$qb->join('e.medicineSalesItems','si');
		$qb->join('si.medicineStock','mds');
		$qb->select('SUM(si.quantity) AS quantity');
		$qb->addSelect('SUM(si.quantity * si.discountPrice ) AS salesPrice');
		$qb->addSelect('SUM(si.quantity * si.purchasePrice ) AS purchasePrice');
		$qb->addSelect('mde.name AS name');
		$qb->where('e.medicineConfig = :config');
		$qb->setParameter('config', $config);
		$qb->andWhere('e.process = :process');
		$qb->setParameter('process', 'Delivered');
		$qb->groupBy('si.medicineStock');
		$qb->orderBy('mde.name','ASC');
		return $qb->getQuery()->getArrayResult();
	}

	public  function reportSalesStockItem(User $user, $data=''){

		$userBranch = $user->getProfile()->getBranches();
		$config =  $user->getGlobalOption()->getMedicineConfig()->getId();
		$group = isset($data['group']) ? $data['group'] :'medicineStock';

		$qb = $this->createQueryBuilder('s');
		$qb->join('e.medicineSalesItems','si');
		$qb->join('si.medicinePurchaseItem','item');
		$qb->join('si.medicineStock','mds');
		$qb->select('SUM(si.quantity) AS quantity','SUM(si.bonusQnt) AS bonusQnt');
		$qb->addSelect('SUM(si.quantity * si.discountPrice ) AS salesPrice');
		$qb->addSelect('SUM(si.quantity * si.purchasePrice ) AS purchasePrice');
		$qb->addSelect('mde.name AS name');
		$qb->where('s.medicineConfig = :config');
		$qb->setParameter('config', $config);
		$qb->andWhere('s.process = :process');
		$qb->setParameter('process', 'Delivered');
		if($group == 'medicinePurchaseItem') {
			$qb->addSelect('item.barcode AS barcode');
		}
		$this->handleSearchStockBetween($qb,$data);
		if ($userBranch){
			$qb->andWhere("s.branches = :branch");
			$qb->setParameter('branch', $userBranch);
		}
		$qb->groupBy('si.'.$group);
		$qb->orderBy('s.created','DESC');
		return $qb;
	}


    public function findWithCommissionOverview(User $user, $data)
    {
        if(empty($data)){
            $datetime = new \DateTime("now");
            $data['startDate'] = $datetime->format('Y-m-d 00:00:00');
            $data['endDate'] = $datetime->format('Y-m-d 23:59:59');
        }else{
            $data['startDate'] = date('Y-m-d 00:00:00',strtotime($data['startDate']));
            $data['endDate'] = date('Y-m-d 23:59:59',strtotime($data['endDate']));
        }


        $config = $user->getGlobalOption()->getBusinessConfig()->getId();
        $qb = $this->createQueryBuilder('e');
        $qb->leftJoin('e.doctorInvoices','ip');
        $qb->leftJoin('ip.assignDoctor','d');
        $qb->select('sum(ip.payment) as paymentTotal');
        $qb->addSelect('d.name as referredName');
        $qb->where('e.businessConfig = :config')->setParameter('config', $config);
        $qb->andWhere('ip.process = :mode')->setParameter('mode', 'Paid');
        if (!empty($data['startDate']) ) {
            $qb->andWhere("ip.updated >= :startDate");
            $qb->setParameter('startDate', $data['startDate'].' 00:00:00');
        }

        if (!empty($data['endDate'])) {
            $qb->andWhere("ip.updated <= :endDate");
            $qb->setParameter('endDate', $data['endDate'].' 23:59:59');
        }

        $qb->groupBy('ip.assignDoctor');
        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }


    public function invoiceLists($config, $data)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.businessConfig = :config')->setParameter('config', $config) ;
        $this->handleSearchBetween($qb,$data);
        $qb->orderBy('e.created','DESC');
        $qb->getQuery();
        return  $qb;
    }
    public function srLedger($config, $data)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.businessConfig = :config')->setParameter('config', $config) ;
        $qb->andWhere('e.srCommission > 0');
        $this->handleSearchBetween($qb,$data);
        $qb->orderBy('e.created','DESC');
        $qb->getQuery();
        return  $qb;
    }

    public function invoiceConditionLists($config, $data)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.businessConfig = :config')->setParameter('config', $config) ;
        $qb->andWhere('e.isCondition = 1');
        $this->handleSearchBetween($qb,$data);
        $qb->orderBy('e.created','DESC');
        $qb->getQuery();
        return  $qb;
    }


	public function monthlySales(User $user , $data =array())
	{

		$config =  $user->getGlobalOption()->getBusinessConfig()->getId();
		$compare = new \DateTime();
		$year =  $compare->format('Y');
		$year = isset($data['year'])? $data['year'] :$year;
		$sql = "SELECT MONTH (sales.created) as month,SUM(sales.total) AS total
                FROM business_invoice as sales
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year
                GROUP BY month ORDER BY month ASC";
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
		$stmt->bindValue('config', $config);
		$stmt->bindValue('process', 'Delivered');
		$stmt->bindValue('year', $year);
		$stmt->execute();
		$result =  $stmt->fetchAll();
		return $result;
	}

    public function dailySales(User $user , $data =array())
    {

        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $compare = new \DateTime();
        $year =  $compare->format('Y');
        $month =  $compare->format('F');
        $year = isset($data['year'])? $data['year'] :$year;
        $month = isset($data['month'])? $data['month'] :$month;
        $sql = "SELECT DAY (sales.created) as day,SUM(sales.total) AS total
                FROM business_invoice as sales
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.updated) =:year AND MONTH (sales.updated) =:month
                GROUP BY day ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Delivered');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $salesDays = array();
        foreach ($result as $row):
            $salesDays[$row['day']]=$row;
        endforeach;
        return $salesDays;


    }


    public function updateInvoiceTotalPrice(BusinessInvoice $invoice)
    {
        $em = $this->_em;
        $total = $em->createQueryBuilder()
            ->from('BusinessBundle:BusinessInvoiceParticular','si')
            ->select('sum(si.subTotal) as subTotal')
            ->where('si.businessInvoice = :invoice')
            ->setParameter('invoice', $invoice ->getId())
            ->getQuery()->getOneOrNullResult();

        $qb1 = $em->createQueryBuilder();
        $qb1->from('BusinessBundle:BusinessInvoiceReturnItem','si')
            ->select("sum(si.subTotal) as subTotal")
            ->where('si.invoice = :invoice')
            ->setParameter('invoice', $invoice ->getId());
        $result1 = $qb1->getQuery()->getOneOrNullResult();

        $returnSubTotal = !empty($result1) ? $result1['subTotal'] :0;
        $subTotal = !empty($total['subTotal']) ? $total['subTotal'] :0;
        if($subTotal > 0){

            if ($invoice->getBusinessConfig()->getVatEnable() == 1 && $invoice->getBusinessConfig()->getVatPercentage() > 0) {
                $totalAmount = ($subTotal- $invoice->getDiscount());
                $vat = $this->getCulculationVat($invoice,$totalAmount);
                $invoice->setVat($vat);
            }
            $invoice->setSubTotal(round($subTotal));
            $invoice->setSalesReturn(round($returnSubTotal));
            $invoice->setDiscount($this->getUpdateDiscount($invoice,$subTotal));
            $total = round($invoice->getSubTotal() + $invoice->getVat() - $invoice->getDiscount() - $returnSubTotal);
            $invoice->setTotal($total);
            $invoice->setDue($invoice->getTotal() - $invoice->getReceived());

        }else{

            $invoice->setSubTotal(0);
            $invoice->setTotal(0);
            $invoice->setDue(0);
            $invoice->setDiscount(0);
            $invoice->setTloPrice(0);
            $invoice->setSalesReturn(0);
            $invoice->setVat(0);
        }

        $em->persist($invoice);
        $em->flush();
        return $invoice;

    }
    public function invoiceDistributionTotalPrice(BusinessInvoice $invoice)
    {
        $em = $this->_em;
        $qb = $em->createQueryBuilder();
        $qb->from('BusinessBundle:BusinessInvoiceParticular','si')
            ->select("sum(si.subTotal) as subTotal","sum(si.tloPrice * si.totalQuantity) as tloPrice","sum(si.quantity) as salesQnt","sum(si.returnQnt) as returnQnt","sum(si.damageQnt) as damageQnt","sum(si.spoilQnt) as spoilQnt","sum(si.totalQuantity) as totalQnt","sum(si.bonusQnt) as bonusQnt")
            ->where('si.businessInvoice = :invoice')
            ->setParameter('invoice', $invoice ->getId());
        $result = $qb->getQuery()->getOneOrNullResult();
        return $result;

    }

    public function updateInvoiceDistributionTotalPrice(BusinessInvoice $invoice)
    {
        $em = $this->_em;
        $qb = $em->createQueryBuilder();
        $qb->from('BusinessBundle:BusinessInvoiceParticular','si')
        ->select("sum(si.subTotal) as subTotal","sum(si.tloTotal) as tloPrice","sum(si.srCommissionTotal) as srCommission","sum(si.quantity) as salesQnt","sum(si.returnQnt) as returnQnt","sum(si.damageQnt) as damageQnt","sum(si.spoilQnt) as spoilQnt","sum(si.totalQuantity) as totalQnt","sum(si.bonusQnt) as bonusQnt")
        ->where('si.businessInvoice = :invoice')
        ->setParameter('invoice', $invoice ->getId());
        $result = $qb->getQuery()->getOneOrNullResult();

        $qb1 = $em->createQueryBuilder();
        $qb1->from('BusinessBundle:BusinessInvoiceReturnItem','si')
            ->select("sum(si.subTotal) as subTotal")
            ->where('si.invoice = :invoice')
            ->setParameter('invoice', $invoice ->getId());
        $result1 = $qb1->getQuery()->getOneOrNullResult();

        $subTotal = !empty($result) ? $result['subTotal'] :0;
        $returnSubTotal = !empty($result1) ? $result1['subTotal'] :0;

        if($subTotal > 0){

            if ($invoice->getBusinessConfig()->getVatEnable() == 1 && $invoice->getBusinessConfig()->getVatPercentage() > 0) {
                $totalAmount = ($subTotal- $invoice->getDiscount());
                $vat = $this->getCulculationVat($invoice,$totalAmount);
                $invoice->setVat($vat);
            }
            $invoice->setSubTotal(round($subTotal,2));
            $invoice->setSalesReturn(round($returnSubTotal,2));
            $invoice->setDiscount($this->getUpdateDiscount($invoice,$subTotal));
            $total = round($invoice->getSubTotal() + $invoice->getVat() - $invoice->getDiscount() - $invoice->getSalesReturn());
            $invoice->setTotal($total);
            $invoice->setTloPrice($result['tloPrice']);
            $invoice->setSrCommission($result['srCommission']);
            $invoice->setDue($invoice->getTotal() - $invoice->getReceived());

        }else{

            $invoice->setSubTotal(0);
            $invoice->setSalesReturn(0);
            $invoice->setTotal(0);
            $invoice->setTloPrice(0);
            $invoice->setSrCommission(0);
            $invoice->setDue(0);
            $invoice->setDiscount(0);
            $invoice->setVat(0);
        }

        $em->persist($invoice);
        $em->flush();
        return $result;

    }

    public function getUpdateDiscount(BusinessInvoice $invoice,$subTotal)
    {
        if($invoice->getDiscountType() == 'flat'){
            $discount = $invoice->getDiscountCalculation();
        }else{
            $discount = ($subTotal * $invoice->getDiscountCalculation())/100;
        }
        return $discount;
    }

    public function getCulculationVat(BusinessInvoice $sales,$totalAmount)
    {
        $vat = ( ($totalAmount * (int)$sales->getBusinessConfig()->getVatPercentage())/100 );
        return round($vat);
    }

    public function salesUserReport( User $user , $data)
    {
        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $qb = $this->createQueryBuilder('e');
        $qb->leftJoin('e.salesBy', 'u');
        $qb->select('u.username as salesBy');
        $qb->addSelect('u.id as userId');
        $qb->addSelect('SUM(e.due) as due');
        $qb->addSelect('SUM(e.subTotal) as subTotal');
        $qb->addSelect('SUM(e.total) as total');
        $qb->addSelect('SUM(e.received) as payment');
        $qb->addSelect('SUM(e.discount) as discount');
        $qb->addSelect('SUM(e.vat) as vat');
        $qb->where('e.businessConfig = :config');
        $qb->setParameter('config', $config);
        $qb->andWhere('e.process IN (:process)');
        $qb->setParameter('process', array('Done','Delivered'));
        $this->handleSearchBetween($qb,$data);
        $qb->groupBy('salesBy');
        $qb->orderBy('total','DESC');
        $result = $qb->getQuery()->getArrayResult();
        return $result;

    }



    public function currentMonthSales(User $user , $data =array())
    {

        $config =  $user->getGlobalOption()->getMedicineConfig()->getId();
        $compare = new \DateTime();
        $year =  $compare->format('Y');
        $month =  $compare->format('m');
        $year = isset($data['year'])? $data['year'] :$year;

        $sql = "SELECT sales.salesBy_id as salesBy, MONTH (sales.created) as month, SUM(sales.total) AS total
                FROM business_invoice as sales
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY month , salesBy ORDER BY salesBy ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Delivered');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        return $result;


    }

    public function salesUserPurchasePriceReport(User $user,$data)
    {
        $config =  $user->getGlobalOption()->getMedicineConfig()->getId();
        $qb = $this->createQueryBuilder('e');
        $qb->leftJoin('e.salesBy', 'u');
        $qb->join('e.businessInvoiceParticulars','si');
        $qb->select('u.username as salesBy');
        $qb->addSelect('SUM(si.totalQuantity * si.purchasePrice ) AS totalPurchaseAmount');
        $qb->where('e.businessConfig = :config');
        $qb->setParameter('config', $config);
        $qb->andWhere('e.process IN (:process)');
        $qb->setParameter('process', array('Done','Delivered'));
        $this->handleSearchBetween($qb,$data);
        $qb->orderBy('totalPurchaseAmount','DESC');
        $qb->groupBy('salesBy');
        $result = $qb->getQuery()->getArrayResult();
        $array= array();
        foreach ($result as $row ){
            $array[$row['salesBy']]= $row['totalPurchaseAmount'];
        }
        return $array;
    }

    public function getCountDailyInvoice($config){

        $qb = $this->createQueryBuilder('e');
        $qb->select('COUNT(e.id) as totalInvoice');
        $qb->where('e.businessConfig = :config')->setParameter('config', $config);
        $compareTo = new \DateTime("now");
        $created =  $compareTo->format('Y-m-d 00:00:00');
        $qb->andWhere("e.created >= :createdStart")->setParameter('createdStart', $created);
        $createdEnd =  $compareTo->format('Y-m-d 23:59:59');
        $qb->andWhere("e.created <= :createdEnd")->setParameter('createdEnd', $createdEnd);
        $result = $qb->getQuery()->getOneOrNullResult();
        return ($result['totalInvoice'])?$result['totalInvoice']:1;
    }

    public function insertApiInvoiceToken(GlobalOption $option , $data){

        $em = $this->_em;
        $conf = $option->getBusinessConfig();
        $sales = new BusinessInvoice();
        $sales->setBusinessConfig($option->getBusinessConfig());
        if($data['customerName'] and $data['customerMobile']){
            $customer = $em->getRepository('DomainUserBundle:Customer')->newExistingCustomerForSales($option,$data['customerMobile'],$data);
            $sales->setCustomer($customer);
        }elseif($data['customerId']){
            $customer = $em->getRepository('DomainUserBundle:Customer')->find($data['customerId']);
            $sales->setCustomer($customer);
        }elseif(empty($data['customerId']) and empty($data['customerName']) ) {
            $customer = $em->getRepository('DomainUserBundle:Customer')->findOneBy(array('globalOption' => $option, 'name' => 'Default'));
            $sales->setCustomer($customer);
        }
        if($data['createdBy']){
            $createdBy = $em->getRepository('UserBundle:User')->find($data['createdBy']);
            $sales->setCreatedBy($createdBy);
        }
        $sales->setComment($data['counterNo']);
        $tokenNo = $this->getCountDailyInvoice($conf->getId())+1;
        $em->persist($sales);
        $em->flush();
        $data = array(
            'invoice' => $sales->getInvoice(),
            'customerId' => $sales->getCustomer()->getId(),
            'customerName' => $sales->getCustomer()->getName(),
            'customerMobile' => $sales->getCustomer()->getMobile(),
            'counterNo' => $sales->getComment(),
            'tokenNo' => $tokenNo,
            'created' => $sales->getCreated()->format('d-m-Y')
        );
        return $data;

    }

    public function getLastInvoiceParticular(Customer $customer){


        $qb = $this->createQueryBuilder('e');
        $qb
            ->select('MAX(e.id)')
            ->where('e.customer = :customer')
            ->setParameter('customer', $customer->getId());
        $lastId = $qb->getQuery()->getSingleScalarResult();
        if (empty($lastId)) {
            return $this->insertAssociation($customer);
        }
        $lastCode =  $this->find($lastId);
        return $lastCode;

    }

    public function insertAssociation(Customer $customer)
    {
        $em = $this->_em;
        $invoice = new BusinessInvoice();
        $invoice->setBusinessConfig($customer->getGlobalOption()->getBusinessConfig());
        $invoice->setCustomer($customer);
        $invoice->setProcess("Deliverd");
        $invoice->setEndDate($customer->getCreated());
        $em->persist($invoice);
        $em->flush();
        return $invoice;

    }

    public function deleteAssociationInvoice(Customer $customer)
    {
        $em = $this->_em;
        $sales = $em->createQuery('DELETE BusinessBundle:BusinessInvoice e WHERE e.customer = '.$customer->getId());
        if($sales){
            $sales->execute();
        }

    }

    public function dailyProductSalesPriceReport(User $user , $data = array())
    {

        $config     =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $compare    = new \DateTime('now');
        $year       =  $compare->format('Y');
        $year       = isset($data['year'])? $data['year'] :$year;
        $month      = isset($data['month'])? $data['month'] : $compare->format('m');
        $sql = "SELECT DAY (sales.created) as day, SUM(salesItem.subTotal) AS total, salesItem.businessParticular_id as stockId
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY day , salesItem.businessParticular_id  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Delivered');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $dailySalesArr = array();
        foreach($result as $row) {
            $id = "{$row['day']}-{$row['stockId']}";
            $dailySalesArr[$id] = $row['total'];
        }

        $sql = "SELECT SUM(salesItem.subTotal) AS total, salesItem.businessParticular_id as stockId
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY salesItem.businessParticular_id";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Delivered');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $salesItemTotal = array();
        foreach($result as $row) {
            $salesItemTotal[$row['stockId']] = $row['total'];
        }

        $sql = "SELECT DAY (sales.created) as day,SUM(salesItem.subTotal) AS total
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY day  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Delivered');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $dailyTotalSalesArr = array();
        foreach($result as $row) {
            $dailyTotalSalesArr[$row['day']] = $row['total'];
        }
        return array('salesItemTotal' => $salesItemTotal,'dailySalesArr' => $dailySalesArr,'dailyTotalSalesArr' => $dailyTotalSalesArr);
    }

    public function monthlyProductSummaryReport(User $user , $data = array())
    {

        $config     =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $compare    = new \DateTime('now');
        $year       =  $compare->format('Y');
        $year       = isset($data['year'])? $data['year'] :$year;
        $month      = isset($data['month'])? $data['month'] : $compare->format('m');
        $process = "'Delivered','Done'";
        $sql = "SELECT DAY (sales.created) as day, SUM(salesItem.quantity) AS total,SUM(salesItem.bonusQnt) AS bonus, salesItem.businessParticular_id as stockId
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                WHERE sales.businessConfig_id = :config AND sales.process IN ($process)  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY day , salesItem.businessParticular_id  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $dailySalesArr = array();
        foreach($result as $row) {
            $id = "{$row['day']}-{$row['stockId']}";
            $dailySalesArr[$id] = $row['total'];
        }

        $purchase = "SELECT DAY (sales.created) as day, SUM(salesItem.quantity) AS total,SUM(salesItem.bonusQuantity) AS bonus, salesItem.businessParticular_id as stockId
                FROM business_purchase_item as salesItem
                JOIN business_purchase as sales ON salesItem.businessPurchase_id = sales.id
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY day , salesItem.businessParticular_id  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($purchase);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Approved');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $dailyPurchaseArr = array();
        foreach($result as $row) {
            $id = "{$row['day']}-{$row['stockId']}";
            $dailyPurchaseArr[$id] = $row['total'];
        }

        $purchaseReturn = "SELECT DAY (sales.created) as day, SUM(salesItem.quantity) AS total, salesItem.businessParticular_id as stockId
                FROM business_purchase_return_item as salesItem
                JOIN business_purchase_return as sales ON salesItem.businessPurchaseReturn_id = sales.id
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY day , salesItem.businessParticular_id  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($purchaseReturn);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Approved');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $dailyPurchaseReturnArr = array();
        foreach($result as $row) {
            $id = "{$row['day']}-{$row['stockId']}";
            $dailyPurchaseReturnArr[$id] = $row['total'];
        }

        $salesReturn = "SELECT DAY (sales.created) as day, SUM(salesItem.quantity) AS total,SUM(salesItem.bonusQuantity) AS bonus, salesItem.particular_id as stockId
                FROM business_invoice_return_item as salesItem
                JOIN business_invoice_return as sales ON salesItem.invoiceReturn_id = sales.id
                WHERE sales.businessConfig_id = :config AND sales.process = :process  AND YEAR(sales.created) =:year AND MONTH(sales.created) =:month
                GROUP BY day , salesItem.particular_id  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($salesReturn);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Approved');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $dailySalesReturnArr = array();
        foreach($result as $row) {
            $id = "{$row['day']}-{$row['stockId']}";
            $dailySalesReturnArr[$id] = $row['total'];
        }

        $damage = "SELECT DAY (salesItem.created) as day, SUM(salesItem.quantity) AS total, salesItem.businessParticular_id as stockId
                FROM business_damage as salesItem
                WHERE salesItem.businessConfig_id = :config AND salesItem.process = :process  AND YEAR(salesItem.created) =:year AND MONTH(salesItem.created) =:month
                GROUP BY day , salesItem.businessParticular_id  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($damage);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('process', 'Approved');
        $stmt->bindValue('year', $year);
        $stmt->bindValue('month', $month);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $damageArr = array();
        foreach($result as $row) {
            $id = "{$row['day']}-{$row['stockId']}";
            $damageArr[$id] = $row['total'];
        }
        return array('dailySalesArr' => $dailySalesArr,'dailyPurchaseArr' => $dailyPurchaseArr,'dailyPurchaseReturnArr' => $dailyPurchaseReturnArr,'dailySalesReturnArr' => $dailySalesReturnArr,'damageArr' => $damageArr);
    }

    public function dailyProductSalesReport(User $user , $data = array())
    {

        $config     =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $compare    = new \DateTime('now');
        $year       =  $compare->format('Y');
        $year       = isset($data['year'])? $data['year'] :$year;
        $month      = isset($data['month'])? $data['month'] : $compare->format('m');
        $process = "'Delivered','Done'";
        $rangeMonth = "{$year}-{$month}";

        $sql = "SELECT DAY (sales.created) as day, SUM(salesItem.quantity) AS total, salesItem.businessParticular_id as stockId
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                WHERE sales.businessConfig_id = :config AND DATE_FORMAT(sales.created,'%Y-%m') = :rangeMonth AND sales.process IN ($process)
                GROUP BY day , salesItem.businessParticular_id  ORDER BY day ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('rangeMonth', $rangeMonth);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $dailySalesArr = array();
        foreach($result as $row) {
            $id = "{$row['day']}-{$row['stockId']}";
            $dailySalesArr[$id] = $row['total'];
        }

        $sql = "SELECT SUM(salesItem.quantity) AS total, salesItem.businessParticular_id as stockId
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                WHERE sales.businessConfig_id = :config AND DATE_FORMAT(sales.created,'%Y-%m') = :rangeMonth AND sales.process IN ($process)
                GROUP BY salesItem.businessParticular_id";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue('config', $config);
        $stmt->bindValue('rangeMonth', $rangeMonth);
        $stmt->execute();
        $result =  $stmt->fetchAll();
        $salesItemTotal = array();
        foreach($result as $row) {
            $salesItemTotal[$row['stockId']] = $row['total'];
        }
        return array('salesItemTotal' => $salesItemTotal,'dailySalesArr' => $dailySalesArr);
    }


    public function customerDailyProductSalesReport(User $user , $data = array())
    {
        $customer       = isset($data['mobile'])? $data['mobile'] :'';
        $month       = isset($data['month'])? $data['month'] :'';
        $year       = isset($data['year'])? $data['year'] :'';
        if($customer){
            $config     =  $user->getGlobalOption()->getBusinessConfig()->getId();
            $compare    = new \DateTime('now');
            $process = "'Delivered','Done'";
            $year       =  $compare->format('Y');

            $year       = isset($data['year'])? $data['year'] :$year;
            $month      = isset($data['month'])? $data['month'] : $compare->format('m');
            $rangeMonth = "{$year}-{$month}";
            $sql = "SELECT DAY (sales.created) as day, SUM(salesItem.quantity) AS quantity,SUM(salesItem.bonusQnt) AS bonus, salesItem.businessParticular_id as stockId
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                JOIN Customer as c ON c.id = sales.customer_id
                WHERE sales.businessConfig_id = :config AND c.mobile = :customer  AND DATE_FORMAT(sales.created,'%Y-%m') = :rangeMonth AND sales.process IN ($process)
                GROUP BY day , salesItem.businessParticular_id  ORDER BY day ASC";
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->bindValue('config', $config);
            $stmt->bindValue('customer', $customer);
            $stmt->bindValue('rangeMonth', $rangeMonth);
            $stmt->execute();
            $result =  $stmt->fetchAll();
            $dailySalesArr = array();
            foreach($result as $row) {
                $id = "{$row['day']}-{$row['stockId']}";
                $dailySalesArr[$id] = $row;
            }

            $sql = "SELECT SUM(salesItem.quantity) AS quantity,SUM(salesItem.bonusQnt) AS bonus, salesItem.businessParticular_id as stockId
                FROM business_invoice_particular as salesItem
                JOIN business_invoice as sales ON salesItem.businessInvoice_id = sales.id
                JOIN Customer as c ON c.id = sales.customer_id
                WHERE sales.businessConfig_id = :config AND c.mobile = :customer  AND DATE_FORMAT(sales.created,'%Y-%m') = :rangeMonth AND sales.process IN ($process)
                GROUP BY salesItem.businessParticular_id";
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->bindValue('config', $config);
            $stmt->bindValue('customer', $customer);
            $stmt->bindValue('rangeMonth', $rangeMonth);
            $stmt->execute();
            $result =  $stmt->fetchAll();
            $salesItemTotal = array();
            foreach($result as $row1) {
                $salesItemTotal[$row1['stockId']] = $row1;
            }

            $config     =  $user->getGlobalOption()->getBusinessConfig()->getId();
            $compare    = new \DateTime('now');
            $year       =  $compare->format('Y');
            $year       = isset($data['year'])? $data['year'] :$year;
            $month      = isset($data['month'])? $data['month'] : $compare->format('m');
            $sql = "SELECT DAY (sales.created) as day, SUM(sales.subTotal) AS subTotal, SUM(sales.total) AS total, SUM(sales.discount) AS discount, SUM(sales.received) AS receive, SUM(sales.due) AS due
                FROM business_invoice as sales
                JOIN Customer as c ON c.id = sales.customer_id
            WHERE sales.businessConfig_id = :config AND c.mobile = :customer  AND DATE_FORMAT(sales.created,'%Y-%m') = :rangeMonth AND sales.process IN ($process)
                     GROUP BY day ORDER BY day ASC";
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->bindValue('config', $config);
            $stmt->bindValue('customer', $customer);
            $stmt->bindValue('rangeMonth', $rangeMonth);
            $stmt->execute();
            $result =  $stmt->fetchAll();
            $dailySalesSummaryArr = array();
            foreach($result as $row) {
                $id = "{$row['day']}";
                $dailySalesSummaryArr[$id] = $row;
            }

            $config     =  $user->getGlobalOption()->getBusinessConfig()->getId();
            $compare    = new \DateTime('now');
            $year       =  $compare->format('Y');
            $year       = isset($data['year'])? $data['year'] :$year;
            $month      = isset($data['month'])? $data['month'] : $compare->format('m');
            $sql = "SELECT SUM(sales.subTotal) AS subTotal, SUM(sales.total) AS total, SUM(sales.discount) AS discount, SUM(sales.received) AS receive, SUM(sales.due) AS due
                FROM business_invoice as sales
                JOIN Customer as c ON c.id = sales.customer_id
                WHERE sales.businessConfig_id = :config AND c.mobile = :customer  AND DATE_FORMAT(sales.created,'%Y-%m') = :rangeMonth AND sales.process IN ($process)
                 ";
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->bindValue('config', $config);
            $stmt->bindValue('customer', $customer);
            $stmt->bindValue('rangeMonth', $rangeMonth);
            $stmt->execute();
            $monthlySalesSummary =  $stmt->fetch();
            return array('salesItemTotal' => $salesItemTotal,'dailySalesArr' => $dailySalesArr,'dailySalesSummaryArr' => $dailySalesSummaryArr,'monthlySalesSummary'=>$monthlySalesSummary);

        }
        return array('salesItemTotal' => '','dailySalesArr' => '','dailySalesSummaryArr'=>'');

    }

    public function salesConditionReport( User $user , $data)
    {
        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.condition', 'i');
        $qb->select('i.id as courierId','i.name as name');
        $qb->addSelect('COUNT(e.id) as invoice');
        $qb->addSelect('SUM(e.total) as total');
        $qb->addSelect('SUM(e.received) as received');
        $qb->where('e.businessConfig = :config');
        $qb->setParameter('config', $config);
        $qb->andWhere('e.process IN (:process)');
        $qb->setParameter('process', array('Received','Condition'));
        $this->handleSearchBetween($qb,$data);
        $qb->groupBy('i.id');
        $qb->orderBy('i.name','DESC');
        $result = $qb->getQuery()->getArrayResult();
        return $result;

    }

    public function salesConditionCustomerReport( User $user , $data)
    {
        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $condition = isset($data['condition'])? $data['condition'] :'';
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.condition', 'i');
        $qb->join('e.customer', 'c');
        $qb->select('c.id as customerId','c.name as name','c.mobile as mobile');
        $qb->addSelect('COUNT(e.id) as invoice');
        $qb->addSelect('SUM(e.total) as total');
        $qb->addSelect('SUM(e.received) as received');
        $qb->where('e.businessConfig = :config');
        $qb->setParameter('config', $config);
        $qb->andWhere('e.process IN (:process)');
        $qb->setParameter('process', array('Received','Delivered','Condition'));
        $qb->andWhere('e.condition = :condition');
        $qb->setParameter('condition',$condition);
        $this->handleSearchBetween($qb,$data);
        $qb->groupBy('c.name');
        $qb->orderBy('c.name','DESC');
        $result = $qb->getQuery()->getArrayResult();

        return $result;

    }

    public function salesConditionDetailsReport( User $user , $data)
    {
        $config =  $user->getGlobalOption()->getBusinessConfig()->getId();
        $condition = isset($data['condition'])? $data['condition'] :'';
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.condition', 'i');
        $qb->join('e.customer', 'c');
        $qb->select('c.id as customerId','c.name as name','c.mobile as mobile');
        $qb->addSelect('e.created as created,e.updated as updated,e.invoice as invoice,e.process as process,e.total as total,e.received as received');
        $qb->addSelect('i.name as condition');
        $qb->where('e.businessConfig = :config');
        $qb->setParameter('config', $config);
        $qb->andWhere('e.process IN (:process)');
        $qb->setParameter('process', array('Received','Delivered','Condition'));
        $qb->andWhere('e.condition = :condition');
        $qb->setParameter('condition',$condition);
        $this->handleSearchBetween($qb,$data);
        $qb->orderBy('c.name','DESC');
        $result = $qb->getQuery()->getArrayResult();

        return $result;

    }

    public function insertFuelSales(BusinessBatchParticular $particular)
    {
        $em = $this->_em;
        $quantity = ($particular->getQuantity() - $particular->getCustomerSalesQuantity());
        $total = ($particular->getPrice() * $quantity);

        $config = $particular->getBusinessBatch()->getBusinessConfig();
        $entity = new BusinessInvoice();
        $entity->setBusinessConfig($config);
        $entity->setCreatedBy($particular->getSalesBy());
        $entity->setSalesBy($particular->getSalesBy());
        $customer = $em->getRepository('DomainUserBundle:Customer')->defaultCustomer($config->getGlobalOption());
        $entity->setCustomer($customer);
        $transactionMethod = $em->getRepository('SettingToolBundle:TransactionMethod')->find(1);
        $entity->setTransactionMethod($transactionMethod);
        $entity->setPaymentStatus('Paid');
        $entity->setProcess("Delivered");
        $entity->setApprovedBy($particular->getSalesBy());
        $entity->setSubTotal($total);
        $entity->setTotal($total);
        $entity->setPayment($total);
        $entity->setReceived($total);
        $em->persist($entity);
        $em->flush();

        $salesItem = new BusinessInvoiceParticular();
        $salesItem->setBusinessInvoice($entity);
        $salesItem->setBusinessParticular($particular->getBusinessParticular());
        $salesItem->setParticular($particular->getBusinessParticular()->getName());
        $salesItem->setWearhouse($particular->getWearhouse());
        $salesItem->setQuantity($quantity);
        $salesItem->setTotalQuantity($quantity);
        $salesItem->setPrice($particular->getPrice());
        $salesItem->setSubTotal($total);
        $em->persist($salesItem);
        $em->flush();
        $em->getRepository('AccountingBundle:AccountSales')->insertBusinessAccountInvoice($entity);
        $em->getRepository('BusinessBundle:BusinessParticular')->getSalesUpdateQnt($salesItem);
        if($entity->getBusinessConfig()->isStockHistory() == 1 ){
            $em->getRepository('BusinessBundle:BusinessStockHistory')->processInsertSalesItem($entity);
        }

    }


}
