<?php

namespace Modules\Inventory\App\Repositories;
use Doctrine\ORM\EntityRepository;
use Modules\Core\App\Models\WarehouseModel;
use Modules\Inventory\App\Entities\Config;
use Modules\Inventory\App\Entities\Sales;
use Modules\Inventory\App\Entities\SalesItem;
use Modules\Inventory\App\Entities\StockItem;


/**
 * ItemTypeGroupingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesItemRepository extends EntityRepository
{

}
