<?php

namespace Core\UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AccessRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRoleRepository extends EntityRepository
{
}
